version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: .docker/sql/Dockerfile
    container_name: saperstonestudios_mysql
    restart: always
    volumes:
    - mysql:/var/lib/mysql
    ports:
    - ${DB_PORT}:3306
    expose:
    - ${DB_PORT}
    environment:
      TZ: "America/New_York"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
  php-myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: saperstonestudios_php-myadmin
    restart: always
    depends_on:
    - mysql
    ports:
    - ${ADMIN_PORT}:80
    expose:
    - ${ADMIN_PORT}
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    links:
    - mysql
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
        MPDF_VERSION: 7.1.9
        PAYPAL_VERSION: 3.9.1
        PAYPAL_USERNAME: ${PAYPAL_USERNAME}
        PAYPAL_PASSWORD: ${PAYPAL_PASSWORD}
        PAYPAL_SIGNATURE: ${PAYPAL_SIGNATURE}
        TWITTER_VERSION: 3.1.0
    container_name: saperstonestudios_php
    restart: always
    depends_on:
    - mysql
    ports:
    - ${HTTP_PORT}:80
    - ${HTTPS_PORT}:443
    expose:
    - ${HTTP_PORT}
    - ${HTTPS_PORT}
    links:
    - mysql
    volumes:
    - ./content:/var/www/content
    - ./logs:/var/www/logs
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      SERVER_NAME: ${SERVER_NAME}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASS}
      EMAIL_USERNAME_BACKUP: ${EMAIL_USER_X}
      EMAIL_PASSWORD_BACKUP: ${EMAIL_PASS_X}
volumes:
  mysql:
