version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: .docker/sql/Dockerfile
    container_name: saperstonestudios_mysql
    restart: always
    volumes:
    - mysql:/var/lib/mysql
    ports:
    - ${DB_PORT}:${DB_PORT}
    expose:
    - ${DB_PORT}
    environment:
      TZ: "America/New_York"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
  php-myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: saperstonestudios_php-myadmin
    restart: always
    depends_on:
    - mysql
    ports:
    - "8080:80"
    expose:
    - 8080
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    links:
    - mysql
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: saperstonestudios_php
    depends_on:
    - mysql
    ports:
    - 80:80
    - 443:443
    expose:
    - 80
    - 443
    links:
    - mysql
    volumes:
    - ./content:/var/www/content
    - ./logs:/var/www/logs
    environment:
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASS}
volumes:
  mysql:
