services:
  mysql:
    image: ghcr.io/msaperst/saperstone-studios/sql:develop
    container_name: saperstonestudios_mysql
    restart: always
    volumes:
    - mysql:/var/lib/mysql
    environment:
      TZ: "America/New_York"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
  php:
    image: ghcr.io/msaperst/saperstone-studios/php:develop
    container_name: saperstonestudios_php
    restart: always
    depends_on:
    - mysql
    ports:
    - ${HTTP_PORT}:80
    - ${HTTPS_PORT}:443
    expose:
    - ${HTTP_PORT}
    - ${HTTPS_PORT}
    links:
    - mysql
    volumes:
    - /mnt/server-data/content:/var/www/content:rw
    - /mnt/server-data/logs:/var/www/logs:rw
    - /mnt/server-data/tmp:/var/www/public/tmp:rw
      #    - /mnt/server-data/apache2/sites-enabled:/etc/apache2/sites-enabled:rw
    - /home/dietpi/certbot/conf:/etc/letsencrypt:rw
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SERVER_NAME: ${SERVER_NAME}
      EMAIL_CONTACT: ${EMAIL_CONTACT}
      EMAIL_ACTIONS: ${EMAIL_ACTIONS}
      EMAIL_SELECTS: ${EMAIL_SELECTS}
      EMAIL_CONTRACTS: ${EMAIL_CONTRACTS}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_USER_X: ${EMAIL_USER_X}
      EMAIL_PASS_X: ${EMAIL_PASS_X}
      CLEAN_UP_AFTER: "604800"
      SEND_EMAIL_AFTER: "300"
volumes:
  mysql:
