--
-- Dumping data for table `reviews`
--

LOCK TABLES `reviews` WRITE;
/*!40000 ALTER TABLE `reviews` DISABLE KEYS */;
INSERT IGNORE INTO `reviews` VALUES (1, 2, 'Wedding', 'Susan and Eugene', 'We hired Leigh Ann of Saperstone Studios in a heartbeat. We had seen a great deal of her work with friends of ours and we didn\'t hesitate to hire her when we were looking for a wedding photographer. She was everywhere during our ceremony, reception, and even in the parking lot when it was all over! She saw a background she wanted and she snagged my husband and me to take some shots as she was packing up her car! What impressed me the most (aside from the amazingly quick turnaround time for receiving our completed photos) was her attention to details that I\'d have never thought of. Including insisting on good posture in the pictures, even the closeups (which definitely made a difference in the finished product). She also has an amazing eye for using light for formal pictures while creating amazing candid shots with that same eye. Our flower girl\'s family ended up with beautiful professional shots just by Leigh Anne catching our flower girl at play. I definitely will be seeking Saperstone Studios for our future needs (anniversary and newborn photo sessions).', '/img/reviews/borelli.jpg');
INSERT IGNORE INTO `reviews` VALUES (2, 1, 'Family Portrait Session', 'Dona', 'My family will attest to the fact that getting my picture taken is not one of my favorite activities.  Last summer the desire for some good family photos made me take the step of setting up a session with Saperstone Studios.  Working with Leigh Ann turned the morning into a fun family outing.   Her relaxed creative approach to the process had us laughing and talking as we walked through a local park stopping to take pictures along the way.   The end result were fantastic family photos that included the six of us and two dogs.  There were so many great family photos it was difficult to choose which ones to print.   We will enjoy them for years to come....and you can be assured that when we need photos in the future....for a small group or a large family reunion we\'ll call Leigh Ann to take the pictures.', '/img/reviews/donna.jpg');
INSERT IGNORE INTO `reviews` VALUES (3, 1, 'Engagement Shoot', 'Helen and Andrew', 'Leigh Ann is an amazing photographer and really made our engagement photo session so special. Not only did the photos turn out beautifully, but Leigh Ann really listened to us and helped us through every step of the process.  She was so helpful in helping us pick the location of the shoot as well as offering great advice about clothing choices, and she was even enthusiastic about my prop ideas. On the day of the photo shoot, Leigh Ann made us feel so comfortable in front of the camera and took her time getting the best shots. She didn\'t rush the shoot and even after several hours of taking photos, she asked us if there was anything else we would like to do. Subjects truly come alive through her photos and I am so happy with how our photos turned out! She is truly a professional and her amazing work speaks for itself. I have been recommending Saperstone Studios to everyone I know!', '/img/reviews/helen.jpg');
INSERT IGNORE INTO `reviews` VALUES (4, 2, 'Wedding', 'Jen and Chris', 'We used Saperstone Studios for our engagement shoot and wedding! Leigh Ann is incredible at what she does and we will use her for all future photo shoots! Starting with the engagement shoot- Leigh Ann made us feel at ease immediately. She was creative in how she posed us and caught us in moments where we didn\'t even realize she was taking shots. The photos turned out beautifully. We had photos that were both serious and fun. She did a great job editing the photos and even used special effects to make one picture look like I was floating away with balloons why my fiancee was holding onto me! We created an album of our engagement pictures because there were that many good shots! For our wedding Leigh Ann continued to impress us! She captured beautiful shots of us, our family and friends! She makes every picture worth 1000 words! We can\'t say enough good things about our experience with Saperstone Studios!', '/img/reviews/jen.jpg');
INSERT IGNORE INTO `reviews` VALUES (5, 1, 'Family Portrait Session', 'Greg and Leah', 'Leigh Ann was the photographer for the Bris of our twin boys and also performed a family photo shoot.  She did an amazing job.  She was very kind and accommodating throughout the shoots.  During the Bris, she managed to get great shots without ever getting in the way of the ceremony, unlike some other photographers that will block everyone\'s view.  Our family photo shoot consisted of our newborn twins and family dog, and Leigh Ann and her helper Max were great with the kids and dog - very patient and got them into great positions looking at the camera.  She also did great work editing the photos after the shoot.  We posed on our carpet in an area with air vents.  Leigh Ann edited out the air vents and other background objects so well that you couldn\'t ever tell there was anything there.  She also gave us digital copies of all of our pictures.  We\'ve printed out a ton, shared them online with family and friends, and used the pictures on holiday cards.  The photo shoot was such a great experience and the pictures all turned out so well, we\'ll definitely be using Leigh Ann whenever we\'re in need of a photographer or updated family pics.', '/img/reviews/roberts.jpg');
INSERT IGNORE INTO `reviews` VALUES (6, 1, 'Family Portrait Session', 'Susan', 'Wow what phenomenal pictures!  We are thrilled! You captured moments I wasn\'t even aware you were watching. Photos are of exceptional quality and the colors are so vibrant.', '/img/reviews/susan.jpg');
/*!40000 ALTER TABLE `reviews` ENABLE KEYS */;
UNLOCK TABLES;