name: API Testing

on:
  pull_request:
    branches: [ develop ]

jobs:
  api_tests:
    name: API Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: imagick

      - name: Set up full-stack test application
        uses: ./.github/actions/setup-full-stack

      - name: System Setup
        run: |
          composer clean
          composer install --prefer-dist --no-progress --no-suggest

      - name: API Tests
        run: COMPOSER_PROCESS_TIMEOUT=1200 composer api-test

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}       # run this step even if previous step failed
        with:
          name: API Tests            # Name of the check run which will be created
          path: reports/api-junit.xml    # Path to test results
          reporter: java-junit        # Format of test results

      - name: Upload HTML test report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: api-test-html
          path: reports/api-results.html
