name: UI Testing

on:
  pull_request:
    branches: [ develop ]

jobs:
  page_tests:
    name: HTTP Page Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: imagick

      - name: Set up full-stack test application
        uses: ./.github/actions/setup-full-stack

      - name: System Setup
        run: |
          composer clean
          composer install --prefer-dist --no-progress --no-suggest

      - name: HTTP Page Tests
        run: composer http-page-test

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}
        with:
          name: HTTP Page Tests
          path: reports/http-page-junit.xml
          reporter: java-junit

      - name: Upload HTML test report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: http-page-test-html
          path: reports/http-page-results.html

      - name: Upload Custom Report 📊
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: http-page
          path: reports

  behat_tests:
    name: Behat Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: imagick

      - name: Set up full-stack test application
        uses: ./.github/actions/setup-full-stack

      - name: System Setup
        run: |
          composer clean
          composer install --prefer-dist --no-progress --no-suggest
          sudo apt-get update -qq
          sudo apt install chromium-chromedriver imagemagick
          chromedriver --port=4444 &

      - name: Behat Tests
        run: COMPOSER_PROCESS_TIMEOUT=1200 composer ui-behat-test

      - name: Upload Custom Report 📊
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: behat
          path: reports
